"use client";
import { defineClientConfig } from "fumadocs-openapi/ui/client";

/**
 * Client-side configuration for Lightfast API documentation
 *
 * Configures the interactive API playground, code samples, and custom UI components
 * for all OpenAPI endpoint pages generated by fumadocs-openapi v10.
 */
export default defineClientConfig({
  /**
   * Storage key prefix for localStorage
   * Prevents conflicts when multiple fumadocs instances exist on the same domain
   */
  storageKeyPrefix: "lightfast-api-docs-",

  /**
   * Playground configuration
   * Controls the interactive "Try It" functionality where users can test API endpoints
   */
  playground: {
    /**
     * Request timeout in seconds
     * Increased from default 10s to 30s because semantic search operations
     * can take longer on large datasets, especially for complex queries with
     * relationship traversal and similarity scoring.
     */
    requestTimeout: 30,

    /**
     * Transform authentication input fields
     * Enhances the UX for bearer token authentication with Lightfast-specific context
     *
     * Future enhancements could include:
     * - Validation for lf_ prefix
     * - Link to lightfast.ai/settings/api-keys
     * - Visual feedback for valid/invalid tokens
     */
    transformAuthInputs: (fields) => {
      return fields.map((field) => {
        // Enhance bearer token input for Lightfast API keys
        if (
          field.original?.type === "http" &&
          field.original.scheme === "bearer"
        ) {
          // Currently returns the field as-is
          // The default implementation handles localStorage persistence
          // Custom UI enhancements can be added here in the future
          return {
            ...field,
          };
        }
        return field;
      });
    },

    /**
     * Custom components for enhanced UX
     *
     * Future enhancements:
     * - ResultDisplay: Format Lightfast-specific responses (search results, relevance scores, source metadata)
     * - Show relationship graph visualizations
     * - Pretty-print error messages with helpful context
     */
    // components: {
    //   ResultDisplay: CustomResultDisplay,
    // },

    /**
     * Custom parameter input rendering
     *
     * Future enhancements:
     * - Autocomplete for common query patterns
     * - Validation hints for required fields
     * - Smart defaults based on endpoint type (search, graph, related)
     */
    // renderParameterField: (fieldName, param) => { ... },
  },

  /**
   * Custom API example selector
   *
   * Future enhancements:
   * - Multiple request scenarios per endpoint
   * - "Basic Search", "Search with Filters", "Pagination" examples
   * - "Graph Traversal" and "Related Events" examples
   */
  // operation: {
  //   APIExampleSelector: CustomExampleSelector,
  // },

  /**
   * Media type adapters for request/response serialization
   *
   * Currently using built-in adapters:
   * - application/json (default, used by all Lightfast endpoints)
   *
   * Custom adapters only needed if we introduce:
   * - XML endpoints
   * - Multipart form data
   * - Custom binary formats
   * - Streaming responses
   */
  // mediaAdapters: {},
});
